apiVersion: v1
kind: Service
metadata:
  name: gitops-service
spec:
  selector:
    app: gitops
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001